title: Arpan Jain
logo: /assets/img/logo.png
description: I have worked in the field of data analysis, data science and financial analysis.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
